name: Build Pre-compiled Wheels

on:
  # Allows you to trigger the build manually from the GitHub Actions tab if needed
  workflow_dispatch:
  # Automatically triggers the build whenever you push a tag starting with 'v'
  push:
    tags:
      - 'v*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # GitHub will boot up 3 separate servers to compile your code
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build wheels using cibuildwheel
        uses: pypa/cibuildwheel@v2.19.0
        # It automatically reads your pyproject.toml settings!

      - name: Upload the compiled wheels
        uses: actions/upload-artifact@v4
        with:
          name: pracpy-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
